// Generated by scripts/generate-cli-version.mjs. Do not edit.
/** npm product version (@deckflow/deckuse-commercial). */
export const productVersion = '1.2.3';
/** Sibling community engine version (@deckflow/deckuse). */
export const engineVersion = '1.4.2';
/** CLI / schema cliVersion — commercial product SemVer. */
export const version = '1.2.3';
