// Generated by scripts/generate-cli-version.mjs. Do not edit.
/** npm product version (@deckflow/deckuse). */
export const productVersion = '1.4.3';
/** Community engine version (@deckflow/deckuse). */
export const engineVersion = '1.4.3';
/** CLI / schema cliVersion. */
export const version = '1.4.3';
